#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 17 16:56:57 2017

@author: nilshoffmann
"""

def test(input):
    value1=input*2
    value2=input**2
    return(value1, value2)
    
print(test(2)[1])